if (build_tests STREQUAL ON)
    file(GLOB_RECURSE test_src "${CMAKE_SOURCE_DIR}/test/*")
    add_executable(${test_name} ${src} ${test_src})
    target_link_libraries(${test_name} ${test_link_dependency})
endif ()
